flow:
  crawl_ths_company:
    flow_content: |
      ReadLocalThsOp(tag="company")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取公司资料信息，例如：详细情况，高管介绍，发行相关，参控股公司，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_holder:
    flow_content: |
      ReadLocalThsOp(tag="holder")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取股东研究信息，例如：股东人数、十大流通股东、十大股东、十大债券持有人、控股层级关系，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_operate:
    flow_content: |
      ReadLocalThsOp(tag="operate")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取经营分析信息，例如：主营介绍、运营业务数据、主营构成分析、主要客户及供应商、董事会经营评述、产品价格，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_equity:
    flow_content: |
      ReadLocalThsOp(tag="equity")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取股本结构信息，例如：解禁时间表、总股本构成、A股结构图、历次股本变动，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_capital:
    flow_content: |
      ReadLocalThsOp(tag="capital")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取资本运作信息，例如：募集资金来源、项目投资、收购兼并、股权投资、参股IPO、股权转让、关联交易、质押解冻，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_worth:
    flow_content: |
      ReadLocalThsOp(tag="worth")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取盈利预测信息，例如：业绩预测、业绩预测详表、研报评级，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_news:
    flow_content: |
      ReadLocalThsOp(tag="news")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取新闻公告信息，例如：新闻与股价联动、公告列表、热点新闻列表、研报列表，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_concept:
    flow_content: |
      ReadLocalThsOp(tag="concept")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取概念题材信息，例如：常规概念、其他概念、题材要点、概念对比，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_position:
    flow_content: |
      ReadLocalThsOp(tag="position")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取主力持仓信息，例如：机构持股汇总、机构持股明细、被举牌情况、IPO获配机构，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_finance:
    flow_content: |
      ReadLocalThsOp(tag="finance")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取财务分析信息，例如：财务诊断、财务指标、指标变动说明、资产负债构成、财务报告、杜邦分析，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_bonus:
    flow_content: |
      ReadLocalThsOp(tag="bonus")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取分红融资信息，例如：分红诊断、分红情况、增发机构获配明细、增发概况、配股概况，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_event:
    flow_content: |
      ReadLocalThsOp(tag="event")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取公司大事信息，例如：高管持股变动、股东持股变动、担保明细、违规处理、机构调研、投资者互动，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true

  crawl_ths_field:
    flow_content: |
      ReadLocalThsOp(tag="field")
    enable_cache: false
    cache_expire_hours: 1
    description: "通过A股股票代码获取行业对比信息，例如：行业地位、行业新闻，最后返回和query相关的信息。"
    input_schema:
      code:
        type: string
        description: "stock code"
        required: true
